from pathlib import Path
import json
import argparse
import shutil
from html import escape
root=Path(__file__).parent
parser=argparse.ArgumentParser(description='Build the protected preview or separate public-ready static output.')
parser.add_argument('--production', action='store_true', help='Write indexable production output to production/; never alters dist/ preview.')
args=parser.parse_args()
output=root/('production' if args.production else 'dist')
output.mkdir(exist_ok=True)
canonical='https://thewelcomebook.co.uk/'
page_title='The Welcome Book | Digital Welcome Guides for Holiday Lets'
page_description='A digital welcome guide for your holiday let. Share property information and local recommendations with guests through a simple QR code.'

icons={
'home':'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3z"/>',
'book':'<path d="M12 5v16M3 3c4 0 6 0 9 2 3-2 5-2 9-2v16c-4 0-6 0-9 2-3-2-5-2-9-2z"/>',
'chat':'<path d="M21 11a9 8 0 0 1-9 8H5l-3 3 1-7a8 8 0 1 1 18-4Z"/><path d="M7 11h.01M12 11h.01M17 11h.01"/>',
'heart':'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
'star':'<circle cx="12" cy="12" r="10"/><path d="m12 5 2.1 4.3 4.7.7-3.4 3.3.8 4.7-4.2-2.2L7.8 18l.8-4.7L5.2 10l4.7-.7z"/>',
'leaf':'<path d="M20 3C6 2 1 10 6 17s16 1 14-14ZM4 21 17 7"/>',
'bed':'<path d="M3 7v14M21 7v14M3 17h18M3 12h18v5M7 12V8h10v4"/>',
'food':'<path d="M5 3v7m4-7v7M3 3v5a4 4 0 0 0 8 0V3M7 12v10M20 22V3c-5 2-5 10 0 10"/>',
'pin':'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
'car':'<path d="m4 10 2-6h12l2 6M3 10h18v8H3zM5 18v3m14-3v3M6 14h2m8 0h2"/>',
'help':'<circle cx="12" cy="12" r="10"/><path d="M9 8a3 3 0 1 1 4 3c-1 0-1 2-1 3m0 3h.01"/>',
'check':'<circle cx="12" cy="12" r="10"/><path d="m7 12 3 3 7-7"/>',
'clipboard':'<path d="M8 5H4v17h16V5h-4M8 3h8v5H8zM8 12h8M8 16h6"/>',
'wave':'<path d="M2 15c5 0 6-10 13-10 4 0 4 4 1 6-2 2-5 0-3-2M2 19c5-4 7-4 11-1s6 1 9-2"/>',
'laptop':'<path d="M5 3h14v13H5zM2 20h20l-3-4H5z"/>'}
def icon(name):return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[name]+'</svg>'
sections=[('home','Welcome','A warm introduction to the property.'),('bed','Your Stay','Wi-Fi, facilities, appliances, house rules, parking, check-in and all the practical details.'),('food','Eat & Drink','Local restaurants, pubs, cafés, takeaways and your own recommendations.'),('pin','Explore','Attractions, walks, activities, days out and useful places nearby.'),('car','Getting Around','Transport, taxis, stations, parking and useful travel information.'),('help','Need Help?','Host details, useful contacts, emergency information and FAQs.'),('clipboard','Checking Out','Departure information and a simple checkout guide.')]
benefits=[('clipboard','Clear Information','Everything your guests need, easy to find.'),('chat','Fewer Questions','Save time with fewer repetitive messages.'),('heart','Happier Guests','A smoother, more enjoyable stay.'),('star','Better Reviews','Well-informed guests can have a better overall experience.'),('leaf','Designed Around You','Your chosen template personalised for your property.')]
styles=[('Country','leaf','Warm, characterful and natural.','For cottages, cabins and countryside stays.'),('Coast','wave','Light, airy and relaxed.','For seaside stays and coastal properties.'),('Modern','home','Clean, restrained and contemporary.','For apartments and modern properties.')]
phone='<div class="phone main-phone" aria-label="Illustrative mobile Welcome Book preview"><div class="notch"></div><img class="phone-logo" src="assets/welcome-book-logo.png" alt="The Welcome Book"><div class="phone-menu">'+''.join('<div>'+icon(i)+'<span>'+t+'</span><span aria-hidden="true">›</span></div>' for i,t,d in sections)+'</div><p>Your stay, made simple.</p></div>'
html='<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">'
html+='<title>'+escape(page_title)+'</title><meta name="description" content="'+escape(page_description,quote=True)+'">'
html+='<meta name="robots" content="'+('index,follow,max-image-preview:large' if args.production else 'noindex,nofollow')+'">'
html+='<link rel="icon" href="favicon.ico" sizes="any"><link rel="icon" type="image/png" sizes="96x96" href="assets/favicon-96.png"><link rel="apple-touch-icon" sizes="180x180" href="assets/apple-touch-icon.png">'
if args.production:
 html+='<link rel="canonical" href="'+canonical+'">'
 social={'og:title':page_title,'og:description':page_description,'og:url':canonical,'og:type':'website','og:site_name':'The Welcome Book','og:locale':'en_GB','og:image':canonical+'og.png','og:image:type':'image/png','og:image:width':'1200','og:image:height':'630','og:image:alt':'The Welcome Book branding beside a welcoming stone cottage with an open green door.'}
 html+=''.join('<meta property="'+key+'" content="'+escape(value,quote=True)+'">' for key,value in social.items())
 twitter={'twitter:card':'summary_large_image','twitter:title':page_title,'twitter:description':page_description,'twitter:image':canonical+'og.png','twitter:image:alt':social['og:image:alt']}
 html+=''.join('<meta name="'+key+'" content="'+escape(value,quote=True)+'">' for key,value in twitter.items())
html+='<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Caveat:wght@400&amp;family=Inter:wght@400;500;600&amp;family=Lora:ital,wght@0,400;0,500;0,600;1,400&amp;display=swap"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script>'

schema={'@context':'https://schema.org','@type':'Service','name':'The Welcome Book','serviceType':'Personalised template-based digital holiday-let welcome guide','areaServed':'United Kingdom','description':'Country, Coast or Modern mobile-first guest guides. £350 one-off includes a digital guide, print-ready PDF and first-year hosting. Professional printing and delivery are optional extras priced on request. Afterwards choose self-hosting or optional £35/year hosting. Later changes available separately.','offers':{'@type':'Offer','price':'350','priceCurrency':'GBP','description':'One-off setup and personalisation, mobile-first digital guide, QR code, print-ready PDF and first-year hosting. Physical printing is not included.'}}
if args.production:
 schema['url']=canonical
 schema['offers']['url']=canonical
html+='<script type="application/ld+json">'+json.dumps(schema)+'</script></head><body><a class="skip-link" href="#main">Skip to content</a><main id="main">'
html+='''<section class="hero" aria-labelledby="hero-heading"><div class="hero-photo" role="img" aria-label="A welcoming stone cottage with an open green door and flowers"></div><div class="container hero-inner"><img class="brand-logo" src="assets/welcome-book-logo.png" alt="The Welcome Book — A beautiful digital guide for your holiday let." width="1536" height="1024"><h1 id="hero-heading">Everything your guests need,<br>in one beautiful place.</h1><p>The Welcome Book is a professionally created digital welcome guide for your holiday let. Important property information, your recommendations and useful details — all in one easy-to-use place.</p><p class="hero-small">Instantly accessible with a QR code. No app to download.</p><a class="button" href="#enquiry">Get your Welcome Book</a><span class="hero-note">A warmer welcome. A smoother stay.</span></div></section>'''
html+='<section class="benefits" aria-label="The benefits"><div class="container benefit-grid">'+''.join('<article>'+icon(i)+'<h2>'+t+'</h2><p>'+d+'</p></article>' for i,t,d in benefits)+'</div></section>'
html+='<section class="inside section" aria-labelledby="inside-heading"><div class="container inside-grid"><div class="device-display"><div class="access-composition"><span class="product-annotation mobile-annotation">Mobile guide<svg viewBox="0 0 60 35" aria-hidden="true"><path d="M3 3Q40 0 53 28m-9-4 10 5 1-11"/></svg></span>'+phone+'<aside class="access-card" aria-label="Illustrative Welcome Book QR card"><span class="access-brand">THE WELCOME<br>BOOK</span><span class="access-instruction">SCAN TO OPEN</span><img src="assets/qr-demonstration.svg" width="100" height="100" alt="Demonstration QR illustration, not a working or scannable code"><span class="access-card-caption">Your digital guide</span></aside><figure class="print-object"><img src="assets/printed-welcome-book.png" alt="Illustrative optional printed Welcome Book with a personalised British holiday-cottage cover" width="1054" height="1492"></figure><span class="product-annotation qr-annotation"><svg viewBox="0 0 45 35" aria-hidden="true"><path d="M7 32Q29 25 27 4m-7 7 7-8 7 8"/></svg>QR access</span><span class="product-annotation print-annotation"><svg viewBox="0 0 45 35" aria-hidden="true"><path d="M38 32Q16 25 18 4m-7 7 7-8 7 8"/></svg>Printed edition</span></div><span class="device-caption">Scan the QR code. Your Welcome Book opens instantly.</span><span class="qr-preview-note">Demonstration only — not scannable.</span></div><div class="inside-copy"><h2 class="section-heading" id="inside-heading">What’s inside your Welcome Book?</h2><p class="section-intro">A little local knowledge. All the practical details.<br>Everything for a relaxed and enjoyable stay.</p><dl class="guide-list">'+''.join('<div>'+icon(i)+'<dt>'+t+'</dt><dd>'+d+'</dd></div>' for i,t,d in sections)+'</dl><p class="inside-note">A mobile-first guide with separate sections, simple navigation and useful actions: open in Maps, visit a website or click to call.</p><div class="product-outputs"><p><strong>Digital Welcome Book</strong><br>Your mobile-first interactive guide, accessed through your property’s QR code.</p><p><strong>Print-ready PDF — included</strong><br>A professionally presented PDF version, yours to keep, email or arrange your own printing.</p><p><strong>Printed Welcome Book — optional extra</strong><br>We can arrange professional printing and delivery of your physical booklet. Options and prices are provided on request, depending on format, page count and quantity.</p></div></div></div></section>'
html+='<section class="styles section" aria-labelledby="styles-heading"><div class="container"><h2 class="section-heading" id="styles-heading">Choose your style</h2><p class="section-intro">Three considered templates. One lovely welcome.<br>Choose your favourite, then we’ll personalise it for your property.</p><div class="style-grid">'
for n,i,d,e in styles:
 html+=f'<article class="style-card {n.lower()}"><div class="phone mini-phone"><div class="notch"></div><div class="style-photo" role="img" aria-label="Illustrative {n.lower()} holiday accommodation"></div><div class="mini-content"><span>WELCOME TO YOUR STAY</span><strong>A warm welcome</strong><p>Make yourself at home.</p><div>{icon("home")} Your Stay</div><div>{icon("food")} Eat & Drink</div><div>{icon("pin")} Explore</div></div></div><div class="style-copy">{icon(i)}<h3>{n}</h3><p>{d}</p><p>{e}</p><button class="style-select" type="button" data-style="{n}" aria-pressed="false">Choose {n}</button></div></article>'
html+='</div><p class="style-footnote">Your photos, property details, welcome message and recommendations — professionally presented in your chosen style. The same useful sections across all three.</p></div></section>'
steps=[('leaf','Choose your style','Choose Country, Coast or Modern.'),('clipboard','Send your details','Share your property information, photographs, recommendations and personal touches.'),('laptop','We build your Welcome Book','We organise and check your supplied content, then present it beautifully in your chosen template.'),('check','Review & go live','Review your guide, request reasonable corrections, and receive your live Welcome Book and QR code.')]
html+='<section class="how section" aria-labelledby="how-heading"><div class="container"><h2 class="section-heading" id="how-heading">How it works</h2><p class="section-intro">A simple process, from start to finish.</p><div class="steps">'+''.join(f'<article><span class="step-number">0{j+1}</span>{icon(i)}<h3>{t}</h3><p>{d}</p></article>' for j,(i,t,d) in enumerate(steps))+'</div></div></section>'
html+='''<section class="pricing section" aria-labelledby="pricing-heading"><div class="container"><h2 class="section-heading" id="pricing-heading">Simple, transparent pricing</h2><p class="section-intro">One-off cost. Long-term flexibility.</p><div class="pricing-grid"><div class="price-card"><h3>The Welcome Book</h3><p class="price">£350</p><span>ONE-OFF PAYMENT</span><p>Your chosen style.<br>Your property’s own welcome.</p><a class="button" href="#enquiry">Get your Welcome Book</a></div><div class="included"><h3>Everything to get you started</h3><ul>'''
html+=''.join('<li>'+icon('check')+s+'</li>' for s in ['Setup using Country, Coast or Modern','Personalisation with your content and photographs','All seven standard Welcome Book sections','Mobile-first digital Welcome Book','Your unique QR code','Print-ready PDF version','First year of Welcome Book hosting','Reasonable pre-launch review and corrections'])
html+='''</ul></div><div class="hosting"><h3>After the first year,<br>the choice is yours.</h3><p><strong>Host it yourself</strong><br>Deploy your Welcome Book on suitable hosting and domain infrastructure.</p><span class="or">OR</span><p><strong>Let us keep it online</strong><br>Optional Welcome Book Hosting for <b>£35 per year.</b></p><p class="hosting-note">You receive and own your finished digital Welcome Book files and PDF. Your guide is portable, with no compulsory monthly subscription and no obligation to stay with our hosting.</p></div></div><div class="print-extra"><h3>Optional printed Welcome Book</h3><p>Professional printing and delivery are available separately and are not included in the £350 price. Printing options and prices are provided on request, depending on format, page count and quantity.</p></div><p class="updates-note">Later updates and changes are available separately, if you need them.</p></div></section>'''
html+='''<section class="enquiry section" id="enquiry" aria-labelledby="enquiry-heading"><div class="container enquiry-grid"><div class="enquiry-copy"><span class="eyebrow">A beautiful stay starts here</span><h2 id="enquiry-heading">Let’s create your<br>Welcome Book.</h2><p>Tell me a little about your property and the style you have in mind. Not sure which to choose? We can work that out together.</p><div class="contact-line">'''+icon('home')+'''<span>For holiday-let owners<br>throughout the UK.</span></div><div class="contact-line"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.12.96.35 1.9.69 2.79a2 2 0 0 1-.45 2.11L8.08 9.89a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.89.34 1.83.57 2.79.69A2 2 0 0 1 22 16.92z"/></svg><a href="tel:+447887505778">07887 505778</a></div><p class="warm-signoff">Great stays start with a warm welcome.</p></div><form id="enquiry-form" method="post" action="/api/enquiry" data-delivery="preview"><div hidden aria-hidden="true"><label>Leave this field empty<input name="website" tabindex="-1" autocomplete="off" maxlength="200"></label></div><div class="form-grid"><label>Name <span aria-hidden="true">*</span><input name="name" autocomplete="name" required maxlength="120"></label><label>Email <span aria-hidden="true">*</span><input type="email" name="email" autocomplete="email" required maxlength="254"></label><label>Property name<input name="propertyName" maxlength="160"></label><label>Property location<input name="propertyLocation" maxlength="160"></label></div><label for="style">Which style are you interested in?</label><select name="style" id="style"><option value="Not sure yet">Not sure yet</option><option>Country</option><option>Coast</option><option>Modern</option></select><label for="message">Tell me about your property <span aria-hidden="true">*</span></label><textarea id="message" name="message" rows="4" required maxlength="5000"></textarea><p class="form-note" id="form-note">Preview only: enquiries are not yet sent. Please don’t enter sensitive information.</p><button class="button submit" type="submit" aria-describedby="form-note">Send enquiry</button><p id="form-status" role="status" tabindex="-1" hidden></p></form></div></section></main><footer><div class="container footer-inner"><div><strong>The Welcome Book</strong><span>A beautiful digital guide for your holiday let.</span></div><p>Website created by <a href="https://signaturewebsitedesigns.co.uk" target="_blank" rel="noopener noreferrer">Signature Website Designs<span class="sr-only"> (opens in a new tab)</span></a></p></div></footer></body></html>'''
if args.production:
 html=html.replace('data-delivery="preview"', 'data-delivery="production"')
 html=html.replace('Preview only: enquiries are not yet sent. Please don’t enter sensitive information.', 'Your details will only be used to respond to your enquiry.')
 shutil.copytree(root/'dist/assets',output/'assets',dirs_exist_ok=True)
 for name in ('styles.css','app.js','favicon.ico','og.png'):
  shutil.copy2(root/'dist'/name,output/name)
 (output/'robots.txt').write_text('User-agent: *\nAllow: /\n\nSitemap: '+canonical+'sitemap.xml\n')
 (output/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>'+canonical+'</loc></url></urlset>\n')
else:
 (output/'robots.txt').write_text('User-agent: *\nDisallow: /\n')
(output/'index.html').write_text(html)
print('Built '+('production/ (indexable; not deployed)' if args.production else 'dist/ (private-preview noindex)'))
